# see https://docs.astral.sh/ruff/configuration/


# Same as Black.
line-length = 88
indent-width = 4


[lint]
# Enable import (`I`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "I"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
