name: Linting

on:
  push:
  pull_request:

jobs:
  lint-with-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install the code linting and formatting tool Ruff
        run: pip install ruff
        
        # run pass-fail test for any lint rule violations
      - name: Lint code with Ruff
        run: ruff check --output-format=github

        # pas-fail test if any formatting would be applied, and output diff
      - name: Check code formatting with Ruff
        run: ruff format --diff
